#Smart Complaint Portal Database Configuration
#Thu Sep 24 01:04:55 IST 2026
db.host=localhost
db.name=smart_complaint_db
db.password=
db.port=3306
db.sqlite.path=smart_complaint.db
db.type=sqlite
db.username=root
